version: "3.8"
services: 
  server: 
    build: 
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - /app/node/modules
      - ./server:/app
  front: 
    build:
      context: ./front
      dockerfile: Dockerfile.dev
    ports: 
      - "3000:3000"
    volumes:
      - /app/node_modules
      - ./front:/app