FROM node:18-alpine

WORKDIR "/app"

COPY ./package.json ./

RUN npm install

COPY . .

CMD ["npm", "start"]

# FROM nginx 
# EXPOSE 4000
# COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf
# COPY --from=0 /app/dist /usr/share/nginx/html