name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p DOCKER_PASSWORD
    - name: Build the Docker image
      run: docker build . --file ./server/Dockerfile --tag kellydouglass/storePratice-server:$(date +%s)
    - name: Docker push
      run: docker push ${{secrets.DOCKER_USER}}//storePractice-server
